services:
  database:
    image: mysql:8
    container_name: adjdb
    environment:
      MYSQL_ROOT: root
      MYSQL_DATABASE: adjdemo
    ports:
      - "3307:3306"
    volumes:
      - adj-volume:/var/lib/mysql
    networks:
      - adj-net
    restart: unless-stopped
  frontend:
    image: client:latest
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8000
        API_BASE: /adj-api
      dockerfile: Dockerfile
    container_name: adj-client
    ports:
      - "3000:80"
    networks:
      - adj-net
    restart: unless-stopped
    depends_on:
      - database
  backend:
    image: server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: adj-server
    environment:
      - SERVER_PORT=8080
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=adjdemo
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "8000:8080"
    networks:
      - adj-net
    depends_on:
      - frontend

volumes:
  adj-volume:
    external: true

networks:
  adj-net:
    external: true